import http from 'node:http';
import https from 'node:https';
import net from 'node:net';
import tls from 'node:tls';
import { spawn } from 'node:child_process';

const port = Number.parseInt(process.env.PORT ?? '8787', 10);
const targetOrigin = process.env.TARGET_ORIGIN ?? 'https://www.freeimages.com';
const allowOrigin = process.env.ALLOW_ORIGIN ?? '*';
const upstreamProxy =
  process.env.HTTPS_PROXY ?? process.env.HTTP_PROXY ?? process.env.ALL_PROXY;
const upstreamFetchMode = (
  process.env.UPSTREAM_FETCH_MODE ?? 'auto'
).toLowerCase();

const hopByHopHeaders = new Set([
  'connection',
  'keep-alive',
  'proxy-authenticate',
  'proxy-authorization',
  'te',
  'trailers',
  'transfer-encoding',
  'upgrade',
]);

function setCorsHeaders(res) {
  res.setHeader('Access-Control-Allow-Origin', allowOrigin);
  res.setHeader('Access-Control-Allow-Methods', 'GET,OPTIONS');
  res.setHeader(
    'Access-Control-Allow-Headers',
    'Content-Type,Accept,Accept-Language,Cache-Control,Pragma',
  );
}

function copyResponseHeaders(upstream, req, res) {
  for (const [key, value] of upstream.headers.entries()) {
    const lower = key.toLowerCase();
    if (hopByHopHeaders.has(lower)) {
      continue;
    }
    if (lower === 'content-encoding') {
      continue;
    }
    if (lower === 'content-length') {
      continue;
    }
    if (lower === 'location') {
      try {
        const redirectUrl = new URL(value, targetOrigin);
        const target = new URL(targetOrigin);
        if (redirectUrl.origin === target.origin) {
          const localOrigin = `http://${req.headers.host}`;
          const localRedirect = new URL(
            `${redirectUrl.pathname}${redirectUrl.search}${redirectUrl.hash}`,
            localOrigin,
          );
          res.setHeader('Location', localRedirect.toString());
          continue;
        }
      } catch {
        // Ignore rewrite failures and keep original header.
      }
    }
    res.setHeader(key, value);
  }
}

function buildUpstreamHeaders(req) {
  const headers = {};
  const incoming = req.headers;
  if (typeof incoming.accept === 'string' && incoming.accept) {
    headers.accept = incoming.accept;
  }
  if (
    typeof incoming['accept-language'] === 'string' &&
    incoming['accept-language']
  ) {
    headers['accept-language'] = incoming['accept-language'];
  }
  if (typeof incoming['cache-control'] === 'string' && incoming['cache-control']) {
    headers['cache-control'] = incoming['cache-control'];
  }
  if (typeof incoming.pragma === 'string' && incoming.pragma) {
    headers.pragma = incoming.pragma;
  }
  headers['user-agent'] =
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36';
  headers.referer = `${targetOrigin}/`;
  return headers;
}

function isCloudFrontGeoBlocked(status, body) {
  if (status !== 403) {
    return false;
  }
  const text = body.toString('utf8');
  return (
    text.includes('Amazon CloudFront distribution is configured to block access from your country') ||
    text.includes('Generated by cloudfront')
  );
}

function parseProxyUrl(raw) {
  if (!raw) {
    return null;
  }
  const url = new URL(raw);
  if (url.protocol !== 'http:' && url.protocol !== 'https:') {
    throw new Error(
      `Unsupported proxy protocol: ${url.protocol}. Only http/https are supported.`,
    );
  }
  return url;
}

function buildProxyAuthHeader(proxyUrl) {
  if (!proxyUrl?.username) {
    return null;
  }
  const user = decodeURIComponent(proxyUrl.username);
  const pass = decodeURIComponent(proxyUrl.password ?? '');
  const encoded = Buffer.from(`${user}:${pass}`).toString('base64');
  return `Basic ${encoded}`;
}

function toHeaders(resHeaders) {
  const headers = new Headers();
  for (const [key, value] of Object.entries(resHeaders)) {
    if (value == null) {
      continue;
    }
    if (Array.isArray(value)) {
      headers.set(key, value.join(', '));
      continue;
    }
    headers.set(key, String(value));
  }
  return headers;
}

function readNodeResponseMessage(res) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    res.on('data', (chunk) => chunks.push(chunk));
    res.on('end', () => {
      resolve({
        status: res.statusCode ?? 502,
        headers: toHeaders(res.headers),
        body: Buffer.concat(chunks),
      });
    });
    res.on('error', reject);
  });
}

function requestViaProxyHttp(targetUrl, requestHeaders, proxyUrl) {
  return new Promise((resolve, reject) => {
    const proxyAuth = buildProxyAuthHeader(proxyUrl);
    const headers = {
      ...requestHeaders,
      host: targetUrl.host,
    };
    if (proxyAuth) {
      headers['proxy-authorization'] = proxyAuth;
    }

    const options = {
      host: proxyUrl.hostname,
      port: Number.parseInt(proxyUrl.port || '80', 10),
      method: 'GET',
      path: targetUrl.toString(),
      headers,
      timeout: 30000,
    };

    const req =
      proxyUrl.protocol === 'https:'
        ? https.request(options)
        : http.request(options);

    req.on('response', async (res) => {
      try {
        resolve(await readNodeResponseMessage(res));
      } catch (error) {
        reject(error);
      }
    });
    req.on('error', reject);
    req.on('timeout', () => {
      req.destroy(new Error('Proxy HTTP request timed out.'));
    });
    req.end();
  });
}

function connectTunnel(proxyUrl, targetHost, targetPort) {
  return new Promise((resolve, reject) => {
    const connectPort = Number.parseInt(
      proxyUrl.port || (proxyUrl.protocol === 'https:' ? '443' : '80'),
      10,
    );
    const socket =
      proxyUrl.protocol === 'https:'
        ? tls.connect({
            host: proxyUrl.hostname,
            port: connectPort,
            servername: proxyUrl.hostname,
          })
        : net.connect({
            host: proxyUrl.hostname,
            port: connectPort,
          });

    const proxyAuth = buildProxyAuthHeader(proxyUrl);

    socket.setTimeout(30000);
    socket.once('timeout', () => {
      socket.destroy(new Error('Proxy CONNECT timed out.'));
    });
    socket.once('error', reject);

    socket.once('connect', () => {
      let connectRequest = `CONNECT ${targetHost}:${targetPort} HTTP/1.1\r\nHost: ${targetHost}:${targetPort}\r\nProxy-Connection: Keep-Alive\r\n`;
      if (proxyAuth) {
        connectRequest += `Proxy-Authorization: ${proxyAuth}\r\n`;
      }
      connectRequest += '\r\n';
      socket.write(connectRequest);
    });

    let responseBuffer = '';
    const onData = (chunk) => {
      responseBuffer += chunk.toString('latin1');
      if (!responseBuffer.includes('\r\n\r\n')) {
        return;
      }

      socket.removeListener('data', onData);
      const firstLine = responseBuffer.split('\r\n', 1)[0] ?? '';
      if (!/HTTP\/1\.[01] 200\b/.test(firstLine)) {
        socket.destroy();
        reject(new Error(`Proxy CONNECT failed: ${firstLine}`));
        return;
      }
      socket.setTimeout(0);

      const tlsSocket = tls.connect({
        socket,
        servername: targetHost,
      });
      tlsSocket.once('error', reject);
      tlsSocket.once('secureConnect', () => {
        resolve(tlsSocket);
      });
    };

    socket.on('data', onData);
  });
}

async function requestViaProxyHttps(targetUrl, requestHeaders, proxyUrl) {
  const targetPort = Number.parseInt(targetUrl.port || '443', 10);
  const tunnelSocket = await connectTunnel(proxyUrl, targetUrl.hostname, targetPort);

  return new Promise((resolve, reject) => {
    const headers = {
      ...requestHeaders,
      host: targetUrl.host,
    };
    const req = https.request({
      host: targetUrl.hostname,
      port: targetPort,
      method: 'GET',
      path: `${targetUrl.pathname}${targetUrl.search}`,
      headers,
      createConnection: () => tunnelSocket,
      agent: false,
      timeout: 30000,
    });

    req.on('response', async (res) => {
      try {
        resolve(await readNodeResponseMessage(res));
      } catch (error) {
        reject(error);
      }
    });
    req.on('error', reject);
    req.on('timeout', () => {
      req.destroy(new Error('Proxy HTTPS request timed out.'));
    });
    req.end();
  });
}

async function requestUpstream(targetUrl, requestHeaders) {
  const proxyUrl = parseProxyUrl(upstreamProxy);
  const useNodeOnly = upstreamFetchMode == 'node';
  const usePowerShellOnly = upstreamFetchMode == 'powershell';

  if (!usePowerShellOnly) {
    const nodeResult = await requestUpstreamByNode(
      targetUrl,
      requestHeaders,
      proxyUrl,
    );
    if (useNodeOnly || !isCloudFrontGeoBlocked(nodeResult.status, nodeResult.body)) {
      return nodeResult;
    }
  }

  return requestViaPowerShell(targetUrl, requestHeaders, proxyUrl);
}

async function requestUpstreamByNode(targetUrl, requestHeaders, proxyUrl) {
  if (!proxyUrl) {
    const upstream = await fetch(targetUrl, {
      method: 'GET',
      headers: requestHeaders,
      redirect: 'follow',
    });
    const body = Buffer.from(await upstream.arrayBuffer());
    return {
      status: upstream.status,
      headers: upstream.headers,
      body,
    };
  }

  if (targetUrl.protocol === 'https:') {
    return requestViaProxyHttps(targetUrl, requestHeaders, proxyUrl);
  }
  return requestViaProxyHttp(targetUrl, requestHeaders, proxyUrl);
}

function requestViaPowerShell(targetUrl, requestHeaders, proxyUrl) {
  return new Promise((resolve, reject) => {
    const psScript = `
$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
$targetUrl = $env:PS_TARGET_URL
$headersJson = $env:PS_HEADERS_JSON
$proxyUrl = $env:PS_PROXY_URL

$headers = @{}
if ($headersJson) {
  $headersObj = ConvertFrom-Json $headersJson
  foreach ($p in $headersObj.PSObject.Properties) {
    if ($null -ne $p.Value -and "$($p.Value)".Length -gt 0) {
      $headers[$p.Name] = [string]$p.Value
    }
  }
}

$status = 502
$content = ''
$responseHeaders = @{}

try {
  if ($proxyUrl) {
    $resp = Invoke-WebRequest -Uri $targetUrl -Method Get -Headers $headers -Proxy $proxyUrl -MaximumRedirection 5 -TimeoutSec 30
  } else {
    $resp = Invoke-WebRequest -Uri $targetUrl -Method Get -Headers $headers -MaximumRedirection 5 -TimeoutSec 30
  }
  $status = [int]$resp.StatusCode
  $content = [string]$resp.Content
  foreach ($key in $resp.Headers.Keys) {
    $responseHeaders[$key] = [string]$resp.Headers[$key]
  }
} catch {
  $webResp = $_.Exception.Response
  if ($null -eq $webResp) {
    throw
  }
  $status = [int]$webResp.StatusCode.value__
  $reader = New-Object System.IO.StreamReader($webResp.GetResponseStream())
  $content = $reader.ReadToEnd()
  $reader.Close()
  foreach ($key in $webResp.Headers.AllKeys) {
    $responseHeaders[$key] = [string]$webResp.Headers[$key]
  }
}

$bodyBytes = [System.Text.Encoding]::UTF8.GetBytes($content)
$output = @{
  status = $status
  headers = $responseHeaders
  bodyBase64 = [System.Convert]::ToBase64String($bodyBytes)
}
Write-Output ('__PS_JSON__' + ($output | ConvertTo-Json -Compress -Depth 8))
`;

    const child = spawn(
      'powershell',
      ['-NoProfile', '-ExecutionPolicy', 'Bypass', '-Command', psScript],
      {
        env: {
          ...process.env,
          PS_TARGET_URL: targetUrl.toString(),
          PS_HEADERS_JSON: JSON.stringify(requestHeaders),
          PS_PROXY_URL: proxyUrl ? proxyUrl.toString() : '',
        },
        windowsHide: true,
      },
    );

    let stdout = '';
    let stderr = '';
    const timeout = setTimeout(() => {
      child.kill('SIGTERM');
      reject(new Error('PowerShell upstream request timed out.'));
    }, 45000);

    child.stdout.on('data', (chunk) => {
      stdout += chunk.toString();
    });
    child.stderr.on('data', (chunk) => {
      stderr += chunk.toString();
    });
    child.on('error', (error) => {
      clearTimeout(timeout);
      reject(error);
    });
    child.on('exit', (code) => {
      clearTimeout(timeout);
      if (code !== 0) {
        reject(
          new Error(
            `PowerShell upstream failed with code ${code}. ${stderr.trim()}`,
          ),
        );
        return;
      }

      const line = stdout
          .split(/\r?\n/)
          .map((x) => x.trim())
          .find((x) => x.startsWith('__PS_JSON__'));
      if (!line) {
        reject(
          new Error(`PowerShell upstream did not return structured output. ${stdout.trim()}`),
        );
        return;
      }

      try {
        const payload = JSON.parse(line.replace('__PS_JSON__', ''));
        const body = Buffer.from(payload.bodyBase64 ?? '', 'base64');
        resolve({
          status: Number(payload.status ?? 502),
          headers: toHeaders(payload.headers ?? {}),
          body,
        });
      } catch (error) {
        reject(error);
      }
    });
  });
}

const server = http.createServer(async (req, res) => {
  setCorsHeaders(res);

  if (req.method === 'OPTIONS') {
    res.statusCode = 204;
    res.end();
    return;
  }

  if (req.url === '/health') {
    res.setHeader('Content-Type', 'application/json; charset=utf-8');
    res.end(
      JSON.stringify({
        ok: true,
        targetOrigin,
        upstreamProxy: upstreamProxy ?? null,
        upstreamFetchMode,
      }),
    );
    return;
  }

  if (req.method !== 'GET') {
    res.statusCode = 405;
    res.setHeader('Content-Type', 'application/json; charset=utf-8');
    res.end(JSON.stringify({ error: 'Only GET is supported.' }));
    return;
  }

  try {
    const incomingUrl = new URL(req.url ?? '/', `http://${req.headers.host}`);
    const targetUrl = new URL(
      `${incomingUrl.pathname}${incomingUrl.search}`,
      targetOrigin,
    );

    const upstream = await requestUpstream(targetUrl, buildUpstreamHeaders(req));

    res.statusCode = upstream.status ?? 502;
    copyResponseHeaders(upstream, req, res);
    res.setHeader('Content-Length', String(upstream.body.length));
    res.end(upstream.body);
  } catch (error) {
    res.statusCode = 502;
    res.setHeader('Content-Type', 'application/json; charset=utf-8');
    res.end(
      JSON.stringify({
        error: 'Proxy request failed.',
        message: error instanceof Error ? error.message : String(error),
      }),
    );
  }
});

server.listen(port, () => {
  // eslint-disable-next-line no-console
  console.log(`FreeImages dev proxy running at http://localhost:${port}`);
  // eslint-disable-next-line no-console
  console.log(`Target origin: ${targetOrigin}`);
  // eslint-disable-next-line no-console
  console.log(
    `Upstream proxy: ${upstreamProxy ? upstreamProxy : '(direct connection)'}`,
  );
  // eslint-disable-next-line no-console
  console.log(`Upstream fetch mode: ${upstreamFetchMode}`);
});
